### ISSUE TITLE
error building vmware image for centos7.1

### ISSUE THREAD

**Issue by mmarseglia** [shiguredo/packer-templates#22]
Hi, 

  I received the following error building the VMware image.
Setup is unable to find the "ifconfig" program on your machine. Please make sure it is installed.

  I found this VMware KB which specifies that the net-tools package must be installed.
http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2075519

  I added the package to the script vmware.sh.

**Comment by hnakamur** [comment]
Hi, @mmarseglia 
Thanks for reporting this issue.
I'm the new mainainer of this project, but I use virtualbox only, not vmware.

Is the diff below what you meant?

```
diff --git a/centos-7.1/scripts/vmware.sh b/centos-7.1/scripts/vmware.sh
index 6b48740..0c7b391 100644
--- a/centos-7.1/scripts/vmware.sh
+++ b/centos-7.1/scripts/vmware.sh
@@ -1,4 +1,4 @@
-yum install -y fuse-libs
+yum install -y fuse-libs net-tools
 mkdir -p /mnt/vmware
 mount -o loop /home/vagrant/linux.iso /mnt/vmware

```

Could you send us a pull request so that you will be listed in https://github.com/shiguredo/packer-templates/graphs/contributors once the pull request is merged?
Thanks!

**Comment by hnakamur** [comment]
I'm closing this issue since there's no update for a long time.
Feel free to reopen this issue when you have a progress.
